Test OG CI: why the hell did it all pass

diff --git a/.github/workflows/PR_validation.yml b/.github/workflows/PR_validation.yml
--- a/.github/workflows/PR_validation.yml
+++ b/.github/workflows/PR_validation.yml
@@ -1,12 +1,6 @@
 name: PR Check
 
-on:
-  pull_request:
-    branches:
-      - main
-    types:
-      - opened       # When a PR is created
-      - edited       # When a PR's title or body is edited
+on: [pull_request]
 
 jobs:
   pr-check:
@@ -73,3 +67,18 @@ jobs:
           echo "EOF" >> $GITHUB_ENV
           echo "STATUS=$STATUS" >> $GITHUB_ENV
 
+      - name: Create or update PR comment
+        uses: peter-evans/create-or-update-comment@v4
+        env:
+          RESULT: ${{ env.RESULT }}
+        with:
+          issue-number: ${{github.event.pull_request.number}}
+          body: |
+            **PR Description Validation Result:**
+            ${{ env.RESULT }}
+      
+      - name: Fail the job if validation check failed
+        if: env.STATUS == 'failure'
+        run: |
+          echo "Failing the job due to validation errors."
+          exit 1
